### ISSUE TITLE
Not compliant to json-rpc specification.

### ISSUE THREAD

**Issue by mjmdavis** [permitio/fastapi_websocket_rpc#21]
Am I correct in assuming that this library is not compliant to the [published specifications](https://www.jsonrpc.org/specification)?

I was thrown when I tried to consume the JSON-RPC endpoint from a different client.

**Comment by orweis** [comment]
Yeah, this has nothing to do with that unofficial RFC working group spec.
It's somewhat similar (as great minds think alike, I guess) - but the protocol here doesn't adhere to that spec.
