### ISSUE TITLE
unnecessary dependency to uvicorn

### ISSUE THREAD

**Issue by WisniewskiP** [permitio/fastapi_websocket_rpc#25]
I think uvicorn could be removed from requirements as it add unneeded dependencies on client side.

fastapi package can be used with uvicorn but doesn't add explicit dependency to it.
```
$ pip show fastapi
Name: fastapi
Version: 0.95.1
Summary: FastAPI framework, high performance, easy to learn, fast to code, ready for production
Home-page:
Author:
Author-email: Sebastián Ramírez <tiangolo@gmail.com>
License:
Location: c:\users\pawelwisniewski\executionplatform\ep\venv-3.10\lib\site-packages
Requires: pydantic, starlette
```

**Comment by orweis** [comment]
Hi @WisniewskiP - I think you're right - though I'll ask for someone on the team to quickly review to be on the safe side.
