### ISSUE TITLE
Binary Types: Any way to support it?

### ISSUE THREAD

**Issue by realoriginal** [permitio/fastapi_websocket_rpc#28]
Idiotic question, is there a suitable way I could achieve being able to support passing binary types to and from the RPC methods on client & server more easily rather than performing the type conversion myself with this library?

**Comment by orweis** [comment]
The arguments passed can be binary buffers. Not sure what you're looking for otherwise.

**Comment by realoriginal** [comment]
It appears as though if I have a method on the server set to say TLDR: `async def my_method( self, my_type : bytes ) -> bytes` - The my_type gets converted to a string ( even if passed as a 'bytes' type client side, and returning 'bytes' via the server returns it as a string to the client.

**Comment by orweis** [comment]
I see what you mean. The wire format is JSON so encoding as strings is
pretty unavoidable. I guess you could potentially add code to check for
bytes and do the casting internally, but it is tantamount to the same thing.

**Comment by realoriginal** [comment]
Fair enough. Thank you.
