### ISSUE TITLE
No support of http_proxy https_proxy

### ISSUE THREAD

**Issue by antoinetran** [permitio/fastapi_websocket_rpc#31]
The framework uses websockets module ([here](https://github.com/permitio/fastapi_websocket_rpc/blob/master/fastapi_websocket_rpc/websocket_rpc_client.py#L8C8-L8C18)).

The websockets module does not support HTTP proxy (see https://github.com/python-websockets/websockets/issues/364, issue from 2018), while websocket-client module ([here](https://pypi.org/project/websocket-client/)) supports it.

Are they plans to migrate websockets implementations though websocket-client instead?

**Comment by orweis** [comment]
Hi @antoinetran - no such plans at the moment.

We would be willing to review a PR, if you'd be interested in  contributing such a feature.
I would also recommend to look at adding an option of using these other websocket implementation and toggling it with a flag, rather than outright migrating

**Comment by antoinetran** [comment]
Ok, I tested a bit and it seems to work! Will do a PR, with a class parameter to choose which Websocket client implementation. By default, it should be the websockets, because it is natively coded as coroutine, but I will ship another class that implements SimpleWebSocket using websocket-client.

I am not sure if my implementation is optimal.

I will also add websocket-client as an dependency of this framework and modify the README a bit to show how to change the implementation to use proxy.

**Comment by racinette** [comment]
@antoinetran Hey, I've created a patch for websockets to use with proxy servers: https://github.com/racinette/websockets_proxy

**Comment by antoinetran** [comment]
> @antoinetran Hey, I've created a patch for websockets to use with proxy servers: https://github.com/racinette/websockets_proxy

Nice! You are free to provide your own websocket client handler to fastapi websocket rpc, in for example your module. But for now, I would rather stick with the official websocket client, and in the future, only the websockets, when their team will fix support of http proxy.

**Comment by mberdyshev** [comment]
Should it be closed now by #32?
