### ISSUE TITLE
Support Unix Domain Sockets (client)

### ISSUE THREAD

**Issue by jdavid** [permitio/fastapi_websocket_rpc#41]
Hi, this is a feature request, to add support for Unix Domain Sockets in WebSocketRpcClient

I think for this unix_connect must be called:
https://websockets.readthedocs.io/en/stable/reference/asyncio/client.html#websockets.client.unix_connect

**Comment by orweis** [comment]
Hi @jdavid - you can create another type of ClientHandler like the ProxyEnabledWebSocketClientHandler [here](https://github.com/permitio/fastapi_websocket_rpc/blob/0e1ec50c28aac9642e88004a76f835f5a995b9cd/fastapi_websocket_rpc/websocket_rpc_client.py#L24) and pass it as `websocket_client_handler_cls` to the constructor. 

You can also open a PR to add this new class to the project.
